[package]
name = "ethercat"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
description = "A Rust implementation of the EtherCAT stack."
